name: chat_app
description: "A group chat Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  page_transition: ^2.1.0
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.1.1
  flutter_keyboard_visibility: ^6.0.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4
  firebase_analytics: ^10.10.6
  font_awesome_flutter: ^10.7.0
  logger: ^2.3.0
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic